<?php
/**
 * @var Mazeapi\VatPrice\Block\Catalog\Product\View\VatPrice $block
 */
?>
<div>
    <span class="price-label">As low as</span>
    <span id="product-price" data-price-amount="<?= $block->getProductFinalPrice() ?>" data-price-type="finalPrice" class="price-wrapper-new">
        <span class="new-price"><?= $block->getProductFormattedPrice() ?></span>
    </span>
    <meta itemprop="price" content="<?= $block->getProductFinalPrice() ?>">
    <meta itemprop="priceCurrency" content="USD">
</div>